package:
  name: pyazr
  version: 1.0

source:
  git_rev: main
  git_url: https://github.com/skowrons94/pyazr

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - iminuit
    - emcee
    - h5py
    - jupyter
    - curses

about:
  home: https://github.com/skowrons94/pyazr
  license: MIT
  license_family: MIT
  summary: A Python interface for AZURE2