package:
  name: pyazr
  version: 1.0

source:
  path: ./

build:
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy

about:
  home: https://github.com/skowrons94/pyazr
  license: MIT
  license_family: MIT
  summary: A Python interface for AZURE2