package:
  name: pyazr
  version: 1.0

source:
  path: ./

build:
  noarch: generic

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - iminuit
    - emcee
    - h5py
    - ncurses
    - azure2

about:
  home: https://github.com/skowrons94/pyazr
  license: MIT
  license_family: MIT
  summary: A Python interface for AZURE2