package:
  name: pyazr
  version: 1.0

source:
  git_rev: main
  git_url: https://github.com/skowrons94/pyazr

requirements:
  build:
    - python
    - setuptools
    - root
    - qt
    - qwt
    - mesalib
    - llvm-openmp
    - gcc
    - cmake
    - make

  run:
    - python
    - numpy=1.24.4
    - scipy
    - matplotlib
    - iminuit
    - emcee
    - h5py
    - ncurses
    - root
    - qt
    - qwt
    - mesalib
    - llvm-openmp

about:
  home: https://github.com/skowrons94/pyazr
  license: MIT
  license_family: MIT
  summary: A Python interface for AZURE2